// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPDZ2NAxXSJHcJtt8lqlPo6DmaYfZoEf4',
    appId: '1:488655790669:web:8bc1f73e1254718c5db204',
    messagingSenderId: '488655790669',
    projectId: 'daycare-app-220c0',
    authDomain: 'daycare-app-220c0.firebaseapp.com',
    storageBucket: 'daycare-app-220c0.firebasestorage.app',
    measurementId: 'G-2MW3XBHWZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Gv8l_Pda1Eii5Qd4rqC0dGzAmGIWeSo',
    appId: '1:488655790669:android:b85c4b7a6ec9f0e05db204',
    messagingSenderId: '488655790669',
    projectId: 'daycare-app-220c0',
    storageBucket: 'daycare-app-220c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQcpjxBX0PU0SIXtJc0FB1IUKjzpNTInk',
    appId: '1:488655790669:ios:35d6cfe306957c415db204',
    messagingSenderId: '488655790669',
    projectId: 'daycare-app-220c0',
    storageBucket: 'daycare-app-220c0.firebasestorage.app',
    iosBundleId: 'com.example.tammniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQcpjxBX0PU0SIXtJc0FB1IUKjzpNTInk',
    appId: '1:488655790669:ios:35d6cfe306957c415db204',
    messagingSenderId: '488655790669',
    projectId: 'daycare-app-220c0',
    storageBucket: 'daycare-app-220c0.firebasestorage.app',
    iosBundleId: 'com.example.tammniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPDZ2NAxXSJHcJtt8lqlPo6DmaYfZoEf4',
    appId: '1:488655790669:web:fbe755eaddbbd3f75db204',
    messagingSenderId: '488655790669',
    projectId: 'daycare-app-220c0',
    authDomain: 'daycare-app-220c0.firebaseapp.com',
    storageBucket: 'daycare-app-220c0.firebasestorage.app',
    measurementId: 'G-HE1PK77XC0',
  );
}
